steps:
  - name: "nixos/nix:latest"
    id: "install-nix-and-build"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        nix build ".#packages.x86_64-linux.default" --extra-experimental-features "nix-command flakes"
        cp -L result /workspace/leaks-finder.tar.gz
  - name: "gcr.io/cloud-builders/docker"
    id: "push-to-registry"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        LOAD_OUTPUT=$(docker load < /workspace/leaks-finder.tar.gz)
        echo "Docker Load Output: $$LOAD_OUTPUT"
        IMAGE_ID=$(echo "$$LOAD_OUTPUT" | awk '/Loaded image/ {print $$3}' | head -n 1)
        if [ -z "$$IMAGE_ID" ]; then
          echo "ERROR: Could not find Image ID in load output."
          exit 1
        fi
        echo "Detected Image ID: $$IMAGE_ID"
        TARGET_IMAGE="us-central1-docker.pkg.dev/pogao-atlantis/leaks-finder/leaks-finder:latest"
        docker tag "$$IMAGE_ID" "$$TARGET_IMAGE"
        DIGEST=$(docker push "$$TARGET_IMAGE" | grep -oP 'sha256:[a-f0-9]+' | tail -1)
        echo "$$DIGEST" > /workspace/image_digest.txt
  - name: "gcr.io/cloud-builders/docker"
    id: "generate-sbom"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        DIGEST=$(cat /workspace/image_digest.txt)
        docker run --rm \
          -v /workspace:/workspace \
          anchore/syft:latest \
          scan "registry:us-central1-docker.pkg.dev/pogao-atlantis/leaks-finder/leaks-finder@$$DIGEST" \
          --output cyclonedx-json=/workspace/sbom.json
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "upload-sbom-to-registry"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        IMAGE_DIGEST=$(cat /workspace/image_digest.txt)
        gcloud artifacts sbom load --source=/workspace/sbom.json --uri="us-central1-docker.pkg.dev/pogao-atlantis/leaks-finder/leaks-finder@$$IMAGE_DIGEST"

images:
  - "us-central1-docker.pkg.dev/pogao-atlantis/leaks-finder/leaks-finder:latest"

options:
  requestedVerifyOption: VERIFIED
  logging: CLOUD_LOGGING_ONLY
